sot_controller:
  control_mode:
    $(arg arm_id)_joint1:
      ros_control_mode: POSITION
      sot_control_mode: VELOCITY
    $(arg arm_id)_joint2:
      ros_control_mode: POSITION
      sot_control_mode: VELOCITY
    $(arg arm_id)_joint3:
      ros_control_mode: POSITION
      sot_control_mode: VELOCITY
    $(arg arm_id)_joint4:
      ros_control_mode: POSITION
      sot_control_mode: VELOCITY
    $(arg arm_id)_joint5:
      ros_control_mode: POSITION
      sot_control_mode: VELOCITY
    $(arg arm_id)_joint6:
      ros_control_mode: POSITION
      sot_control_mode: VELOCITY
    $(arg arm_id)_joint7:
      ros_control_mode: POSITION
      sot_control_mode: VELOCITY

  joint_names:
    [$(arg arm_id)_joint1, $(arg arm_id)_joint2, $(arg arm_id)_joint3,
    $(arg arm_id)_joint4, $(arg arm_id)_joint5, $(arg arm_id)_joint6,
    $(arg arm_id)_joint7]
  joints:
    [$(arg arm_id)_joint1, $(arg arm_id)_joint2, $(arg arm_id)_joint3,
    $(arg arm_id)_joint4, $(arg arm_id)_joint5, $(arg arm_id)_joint6,
    $(arg arm_id)_joint7]
sot:
  state_vector_map:
    [$(arg arm_id)_joint1, $(arg arm_id)_joint2, $(arg arm_id)_joint3,
    $(arg arm_id)_joint4, $(arg arm_id)_joint5, $(arg arm_id)_joint6,
    $(arg arm_id)_joint7]
