sot_controller:
  control_mode:
    shoulder_pan_joint:
      ros_control_mode: POSITION
      sot_control_mode: VELOCITY
    shoulder_lift_joint:
      ros_control_mode: POSITION
      sot_control_mode: VELOCITY
    elbow_joint:
      ros_control_mode: POSITION
      sot_control_mode: VELOCITY
    wrist_1_joint:
      ros_control_mode: POSITION
      sot_control_mode: VELOCITY
    wrist_2_joint:
      ros_control_mode: POSITION
      sot_control_mode: VELOCITY
    wrist_3_joint:
      ros_control_mode: POSITION
      sot_control_mode: VELOCITY

  joint_names:
    [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint,
    wrist_2_joint, wrist_3_joint]
  joints:
    [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint,
    wrist_2_joint, wrist_3_joint]

sot:
  state_vector_map:
    [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint,
    wrist_2_joint, wrist_3_joint]
